CarTrack/device/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from CarTrack import db
from CarTrack.models import Device,User, DeviceLink
from CarTrack.device.forms import AddTrackerForm, ManageDeviceForm, ShareTrackerForm

device = Blueprint('device', __name__)

@device.route('/add_device', methods=['POST', 'GET'])
@login_required
def add_device():
    form = AddTrackerForm()
    if form.validate_on_submit():
        device = Device(name=form.device_name.data,color=form.device_color.data,
                        device_id=form.device_id.data,password=form.device_password.data)
        db.session.add(device)
        db.session.commit()
        link = DeviceLink(user_id=current_user.id, device_id=device.id, mode="owner")
        db.session.add(link)
        db.session.commit()
        flash('Device added successfully!','success')
        return redirect(url_for('main.home'))
    return render_template('add_device.html', title="Add Device", form=form)

@device.route('/share_device', methods=['POST', 'GET'])
@login_required
def share_device():
    form = ShareTrackerForm()
    form.device.choices = []
    device_id_list = DeviceLink.query.join(User).filter(User.id == current_user.id)\
        .filter(DeviceLink.mode == "owner").all()
    for i in device_id_list:
        cur = Device.query.filter_by(id=i.device_id).first()
        form.device.choices.append(cur)
    if form.validate_on_submit():
        selected_device = None
        for i in device_id_list:
            cur = Device.query.filter_by(id=i.device_id).first()
            if cur.name == form.device.data:
                selected_device = cur.id
        if selected_device.password == form.password.data:
            if selected_device is not None:
                shared_user = User.query.filter_by(username=form.username.data).first()
                link = DeviceLink(user_id=shared_user.id, device_id=selected_device.id, mode="guest")
                db.session.add(link)
                db.session.commit()
                flash('Device shared successfully!','success')
                return redirect(url_for('main.home'))
            else:
                flash('Device Cannot be found This should not happen','danger')
                return redirect(url_for('main.home'))
    return render_template('share_device.html', title="Share Device", form=form)

@device.route('/settings/<int:user_id>', methods=['GET', 'POST'])
@login_required
def settings(user_id):
    if user_id != current_user.id:
        flash('You cannot edit other users settings!','danger')
        return redirect(url_for('main.home'))
    user = User.query.get_or_404(user_id)
    # queries are used to get the device objects of the user and bind them to the link
    # query to find devices that are belong to the user
    my_device = []
    for i in DeviceLink.query.join(User).filter(User.id == user.id).filter(DeviceLink.mode == "owner").all():
        my_device.append(Device.query.filter_by(id=i.device_id).first())
    # query to find devices that are shared with the user
    shared_device = []
    for i in DeviceLink.query.join(User).filter(User.id == user.id).filter(DeviceLink.mode == "guest").all():
        shared_device.append(Device.query.filter_by(id=i.device_id).first())
    return render_template('device_settings.html', title="Device Settings", my_device=my_device, shared_device=shared_device)

@device.route('/manage_device/<int:device_id>', methods=['GET', 'POST'])
@login_required
def manage_devices(device_id):
    # device id is number in the id column of the device table
    device = Device.query.get_or_404(device_id)
    owner_id = DeviceLink.query.filter_by(device_id=device.id).filter_by(mode="owner").first().user_id
    if owner_id != current_user.id:
        flash('You cannot manage other users devices!','danger')
        return redirect(url_for('main.home'))
    else:
        form = ManageDeviceForm()
        if form.validate_on_submit():
            if form.old_device_password.data == device.password or device.password == None:
                device.name = form.device_name.data
                device.color = form.device_color.data
                device.password = form.device_password.data
                db.session.commit()
                flash('Device updated successfully!','success')
                return redirect(url_for('device.settings', user_id=current_user.id))
            else:
                flash('Incorrect password!','danger')
                return redirect(url_for('device.manage_devices', device_id=device.id))
        elif request.method == 'GET':
            form.device_name.data = device.name
            form.device_color.data = device.color
        return render_template('manage_device.html', title="Manage Device", device=device, form=form)

CarTrack/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user
from CarTrack.models import User, DeviceLink, Device
main = Blueprint('main', __name__)

@main.route('/')
def home():
    if current_user.is_authenticated:
        my_device = []
        for i in DeviceLink.query.join(User).filter(User.id == current_user.id).filter(DeviceLink.mode == "owner").all():
            my_device.append(Device.query.filter_by(id=i.device_id).first())
        # query to find devices that are shared with the user
        shared_device = []
        for i in DeviceLink.query.join(User).filter(User.id == current_user.id).filter(DeviceLink.mode == "guest").all():
            shared_device.append(Device.query.filter_by(id=i.device_id).first())
        return render_template('home.html', title='Home', my_tracker=my_device, shared_tracker=shared_device)
    return render_template('home.html', title='Home')

CarTrack/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user, login_user, logout_user

from CarTrack import db, bcrypt
from CarTrack.models import User
from CarTrack.users.forms import RegistrationForm, LoginForm, EditProfileForm
from CarTrack.users.utils import save_picture

users = Blueprint('users', __name__)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html',title='Login',form=form)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html',title='Register',form=form)

@users.route('/profile/<int:id>',methods=['GET','POST'])
@login_required
def profile(id):
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    if id == current_user.id:
        # if the user is viewing their own profile render form
        form = EditProfileForm()
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = save_picture(form.picture.data)
                current_user.image_file = picture_file
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.password = form.new_password.data
            db.session.commit()
            flash('Your changes have been saved.', 'success')
            return redirect(url_for('users.profile', id=current_user.id))
        elif request.method == "GET":
            form.username.data = current_user.username
            form.email.data = current_user.email
            return render_template('profile.html', title='Profile', form=form,user=current_user, image_file=image_file)
    else:
        # if the user is not viewing their own profile render the profile page
        user = User.query.get_or_404(id)
        return render_template('profile.html',title='Profile', image_file=image_file, user=user)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

CarTrack/templates/add_device.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-sm">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-light">Add Device</legend>
                <div class="form-group">
                    {{ form.device_name.label(class="form-control-label text-light") }}
                    {% if form.device_name.errors %}
                        {{ form.device_name(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.device_color.label(class="form-control-label text-light") }}
                    {% if form.device_color.errors %}
                        {{ form.device_color(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_color.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_color(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.device_id.label(class="form-control-label text-light") }}
                    {% if form.device_id.errors %}
                        {{ form.device_id(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.device_password.label(class="form-control-label text-light") }}
                    {% if form.device_password.errors %}
                        {{ form.device_password(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_device_password.label(class="form-control-label text-light") }}
                    {% if form.confirm_device_password.errors %}
                        {{ form.confirm_device_password(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_device_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_device_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Add Device</button>
            </div>
        </form>
    </div>
{% endblock %}

CarTrack/templates/device_settings.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-sm">
        <div class="row">
            <div class="col-sm-12">
                <p class="text-light h1 text-center mb-5 pb-5">Device Settings</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 parent">
                <p class="h2 text-light text-center mb-4">Your Devices</p>
            <p class="small">Click The Name To Manage</p>
                {% for device in my_device %}
                    <a href="{{ url_for("device.manage_devices",device_id=device.id) }}">
                        <p class="text-light text-center w-100">
                            {{ device.name }}
                        </p>
                    </a>
                {% endfor %}
            </div>
            <div class="col-sm-6 m-0">
                <p class="h2 text-light text-center mb-4">Devices Shared With You</p>
                <p class="small">You Cannot Manage These</p>
                {% for device in shared_device %}
                    <p class="text-light text-center w-100"> {{ device.name }} </p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

CarTrack/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2 bg-dark" style="height: 100vh">
                    <p class="h2 text-light p-2 mb-4">Hello {{ current_user.username }}</p>
                    <div class="accordion" id="accordionPanelsStayOpenExample">
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header " id="panelsStayOpen-headingOne">
                                <button class="accordion-button bg-dark text-light border-0 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                                    My Trackers
                                </button>
                            </h2>
                            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
                                <div class="accordion-body bg-dark">
                                    {% for i in my_tracker %}
                                        <div class="d-flex flex-column align-items-center">
                                            <button class="btn text-light" onclick="display_map({{ i.id }})">{{ i.name }}</button>
                                        </div>
                                    {% endfor %}
                                    <div class="d-flex flex-column align-items-center">
                                        <a class="text-light text-decoration-none" href="{{ url_for("device.add_device") }}">
                                            <p class="text-light">Add Trackers</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                                <button class="accordion-button bg-dark text-light border-0 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                                    Shared Trackers
                                </button>
                            </h2>
                            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                                <div class="accordion-body bg-dark">
                                    {% for i in shared_tracker %}
                                        <div class="d-flex flex-column align-items-center">
                                                <button class="btn text-light" onclick="display_map({{ i.id }})">{{ i.name }}</button>
                                        </div>
                                    {% endfor %}
                                    <div class="d-flex flex-column align-items-center">
                                        <a class="text-light text-decoration-none" href="{{ url_for("device.share_device") }}">
                                            <p class="text-light">Share Trackers</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="fixed-bottom col-md-2 d-flex flex-column ">
                        <a href="{{ url_for("device.settings",user_id=current_user.id) }}" class="btn btn-bg text-light mt-3 ml-2">Device Settings</a>
                        <a href="{{ url_for("users.logout") }}" class="btn btn-bg text-light mt-3 ml-2">Logout</a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="d-flex justify-content-center">
                        <div id='map' class="p-0 m-0" style='width: 100vw; height:100vh;'></div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="d-flex align-items-center  justify-content-center w-100 h-100">
            <div class="border border-light rounded p-5 m-5 d-flex flex-column">
                <p class="h1 text-light text-center">
                    To Use Our Service Please Sign In
                </p>
                <a href="{{ url_for('users.login') }}" class="text-light btn btn-primary">Sign In</a>
            </div>
        </div>
    {% endif %}
    <script src="{{ url_for("static",filename="drawMap.js") }}"></script>
{% endblock %}

CarTrack/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static',filename="style.css") }}">
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
    <link rel="icon" type="ico" href="{{ url_for("static",filename="icon.ico") }}">
	<link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />

    <title>{{ title }}</title>
</head>
<body {% if title != "Home" or (title == "Home" and not current_user.is_authenticated ) %} class="bg-dark" style="height: 100vh" {% endif %}>
    {% if title != "Home" %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand " href="{{ url_for('main.home') }}">CarTrack</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
            </li>
              {% if current_user.is_authenticated %}
                  <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{ url_for('users.profile',id=current_user.id) }}">Profile</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endif %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

CarTrack/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-sm">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-light">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label text-light") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label text-light mt-2") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check text-light mt-2">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-4">
                    <a href="#">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content%}

CarTrack/templates/manage_device.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-sm">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-light">Manage {{ device.name }}</legend>
                <div class="form-group">
                    {{ form.device_name.label(class="form-control-label text-light") }}
                    {% if form.device_name.errors %}
                        {{ form.device_name(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.device_color.label(class="form-control-label text-light mt-2") }}
                    {% if form.device_color.errors %}
                        {{ form.device_color(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_color.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_color(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.old_device_password.label(class="form-control-label text-light mt-2") }}
                    {% if form.old_device_password.errors %}
                        {{ form.old_device_password(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.old_device_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.old_device_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.device_password.label(class="form-control-label text-light mt-2") }}
                    {% if form.device_password.errors %}
                        {{ form.device_password(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.device_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.device_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_device_password.label(class="form-control-label text-light mt-2") }}
                    {% if form.confirm_device_password.errors %}
                        {{ form.confirm_device_password(class="form-control form-control-lg is-invalid mt-2") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_device_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_device_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-4">
                    <a href="#">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
{% endblock %}

CarTrack/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-sm">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-light">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label text-light") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label text-light text-light") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label text-light") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label text-light") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
            </small>
        </div>
    </div>
    
{% endblock content %}